import operator
from typing import Annotated, List, TypedDict


class AgentState(TypedDict):
    # Using Annotated with operator.add ensures that messages are appended to the history rather than overwriting it
    messages: Annotated[
        List[str], operator.add
    ]  # Message is to maintain state of the Agent - AI Messages, System Messages, User Messages, Tool Messages
    current_query: str  # Current query being processed
    documents: List[str]  # Retrieved documents
    plan: List[str]  # Plan is to know where to go next
    status: str  # Status of the agent (example currently in which Node - our project will have 3 Nodes - Planner Node (Intent Classification), Retriever Node (Vector Search), Responder Node (Generates the final answer))
    final_answer: str  # Final answer generated by the agent
